AWSTemplateFormatVersion: 2010-09-09

Description: Infrastructure for AWS API Gateway, AWS Lambda and AWS DynamoDb

Parameters:
  ApiResourcePath:
    Type: String
    Description: Resource path for AWS API Gateway
    Default: dynamodbmanager

  ApiFunctionKey:
    Description: S3 object key for the API function javascript script
    Type: String

  DynamoDBTableName:
    Description: S3 object key for the API function javascript script
    Type: String

Resources:
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: GSI
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableClass: STANDARD
      TableName: !Ref DynamoDBTableName

  AddOffer:
    Type: Custom::InitFunction
    DependsOn: DynamoDB
    Properties:
      ServiceToken: !GetAtt InitFunction.Arn
      Dtype: "offer"
      Dname: "Super Duper Offer"
      Did: "d9b1d9ff-543e-47c7-895f-87f71dcad91b"
      DbrandId: "692126c8-6e72-4ad7-8a73-25fc2f1f56e4"

  AddLocation1:
    Type: Custom::InitFunction
    DependsOn: DynamoDB
    Properties:
      ServiceToken: !GetAtt InitFunction.Arn
      Dtype: "location"
      Did: "03665f6d-27e2-4e69-aa9b-5b39d03e5f59"
      Daddress: "Address 1"
      DbrandId: "692126c8-6e72-4ad7-8a73-25fc2f1f56e4"

  AddLocation2:
    Type: Custom::InitFunction
    DependsOn: DynamoDB
    Properties:
      ServiceToken: !GetAtt InitFunction.Arn
      Dtype: "location"
      Did: "706ef281-e00f-4288-9a84-973aeb29636e"
      Daddress: "Address 2"
      DbrandId: "692126c8-6e72-4ad7-8a73-25fc2f1f56e4"

  AddLocation3:
    Type: Custom::InitFunction
    DependsOn: DynamoDB
    Properties:
      ServiceToken: !GetAtt InitFunction.Arn
      Dtype: "location"
      Did: "1c7a27de-4bbd-4d63-a5ec-2eae5a0f1870"
      Daddress: "Address 3"
      DbrandId: "692126c8-6e72-4ad7-8a73-25fc2f1f56e4"

  InitFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          DynamoDBTableName: !Ref DynamoDBTableName
      Code:
        ZipFile: |
          const AWS = require("aws-sdk");
          const response = require("./cfn-response");
          const dynamo = new AWS.DynamoDB();
          const tableName = process.env.DynamoDBTableName;

          exports.handler = function (event, context) {
            if (event.RequestType == "Create" || event.RequestType == "Update") {
              if (event.ResourceProperties.Dtype == "location") {
                var params = {
                  Item: {
                    PK: {
                      S: event.ResourceProperties.Did,
                    },
                    SK: {
                      S: event.ResourceProperties.Did,
                    },
                    address: {
                      S: event.ResourceProperties.Daddress,
                    },
                    brandId: {
                      S: event.ResourceProperties.DbrandId,
                    },
                    hasOffer: {
                      BOOL: false,
                    },
                  },
                  TableName: tableName,
                };
              } else {
                var params = {
                  Item: {
                    PK: {
                      S: event.ResourceProperties.Did,
                    },
                    SK: {
                      S: event.ResourceProperties.Did,
                    },
                    name: {
                      S: event.ResourceProperties.Dname,
                    },
                    brandId: {
                      S: event.ResourceProperties.DbrandId,
                    },
                    locationsTotal: {
                      N: "0",
                    },
                  },
                  TableName: tableName,
                };
              }
              dynamo.putItem(params, function (err, data) {
                if (err) {
                  response.send(event, context, "FAILED", { params: params, err: err });
                } else {
                  response.send(event, context, "SUCCESS", { params: params });
                }
              });
            }

            if (event.RequestType == "Delete") {
              response.send(event, context, "SUCCESS", {});
            }
          };
      Handler: index.handler
      Role: !ImportValue LambdaIAMRole
      Runtime: nodejs16.x
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue SummitVPCSG
        SubnetIds:
          - !ImportValue SummitSubnet1
          - !ImportValue SummitSubnet2

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: aws-dnb-tech-summit-2024-api
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      RestApiId: !Ref ApiGatewayRestApi
      PathPart: !Ref ApiResourcePath

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2024-10-24/functions/${ApiLambdaFunction.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.Content-Length: integration.response.header.Content-Length
            ResponseTemplates:
              application/json: |
                $input.json('$')
        RequestTemplates:
          application/json: |
            #set($allParams = $input.params()) {
              "body" : $input.json('$'),
              "params" : {
              #foreach($type in $allParams.keySet())
                  #set($params = $allParams.get($type))
              "$type" : {
                  #foreach($paramName in $params.keySet())
                  "$paramName" : "$util.escapeJavaScript($params.get($paramName))"
                      #if($foreach.hasNext),#end
                  #end
              }
                  #if($foreach.hasNext),#end
              #end
              },
              "method": "$context.httpMethod",
              "uri" : "$context.resourcePath"
            }
        PassthroughBehavior: WHEN_NO_TEMPLATES
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Content-Type: true
            method.response.header.Content-Length: true
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi

  ApiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          DynamoDBTableName: !Ref DynamoDBTableName
      Code:
        S3Bucket: !ImportValue ScriptBucket
        S3Key: !Ref ApiFunctionKey
      Handler: ApiLambdaFunction.handler
      Role: !ImportValue LambdaIAMRole
      Runtime: nodejs16.x
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue SummitVPCSG
        SubnetIds:
          - !ImportValue SummitSubnet1
          - !ImportValue SummitSubnet2

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ApiLambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: "apigateway.amazonaws.com"

Outputs:
  ApiGatewayInvokeURL:
    Value: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStage}/${ApiResourcePath}
